package com.duing.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Play {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column play.id
     *
     * @mbg.generated Fri Jun 25 12:16:42 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column play.play_id
     *
     * @mbg.generated Fri Jun 25 12:16:42 CST 2021
     */
    private String playId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column play.play_time
     *
     * @mbg.generated Fri Jun 25 12:16:42 CST 2021
     */
    private Date playTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column play.lan_type
     *
     * @mbg.generated Fri Jun 25 12:16:42 CST 2021
     */
    private String lanType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column play.price
     *
     * @mbg.generated Fri Jun 25 12:16:42 CST 2021
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column play.room_id
     *
     * @mbg.generated Fri Jun 25 12:16:42 CST 2021
     */
    private String roomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column play.room_name
     *
     * @mbg.generated Fri Jun 25 12:16:42 CST 2021
     */
    private String roomName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column play.film_id
     *
     * @mbg.generated Fri Jun 25 12:16:42 CST 2021
     */
    private String filmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column play.film_name
     *
     * @mbg.generated Fri Jun 25 12:16:42 CST 2021
     */
    private String filmName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column play.id
     *
     * @return the value of play.id
     *
     * @mbg.generated Fri Jun 25 12:16:42 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column play.id
     *
     * @param id the value for play.id
     *
     * @mbg.generated Fri Jun 25 12:16:42 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column play.play_id
     *
     * @return the value of play.play_id
     *
     * @mbg.generated Fri Jun 25 12:16:42 CST 2021
     */
    public String getPlayId() {
        return playId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column play.play_id
     *
     * @param playId the value for play.play_id
     *
     * @mbg.generated Fri Jun 25 12:16:42 CST 2021
     */
    public void setPlayId(String playId) {
        this.playId = playId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column play.play_time
     *
     * @return the value of play.play_time
     *
     * @mbg.generated Fri Jun 25 12:16:42 CST 2021
     */
    public Date getPlayTime() {
        return playTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column play.play_time
     *
     * @param playTime the value for play.play_time
     *
     * @mbg.generated Fri Jun 25 12:16:42 CST 2021
     */
    public void setPlayTime(Date playTime) {
        this.playTime = playTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column play.lan_type
     *
     * @return the value of play.lan_type
     *
     * @mbg.generated Fri Jun 25 12:16:42 CST 2021
     */
    public String getLanType() {
        return lanType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column play.lan_type
     *
     * @param lanType the value for play.lan_type
     *
     * @mbg.generated Fri Jun 25 12:16:42 CST 2021
     */
    public void setLanType(String lanType) {
        this.lanType = lanType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column play.price
     *
     * @return the value of play.price
     *
     * @mbg.generated Fri Jun 25 12:16:42 CST 2021
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column play.price
     *
     * @param price the value for play.price
     *
     * @mbg.generated Fri Jun 25 12:16:42 CST 2021
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column play.room_id
     *
     * @return the value of play.room_id
     *
     * @mbg.generated Fri Jun 25 12:16:42 CST 2021
     */
    public String getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column play.room_id
     *
     * @param roomId the value for play.room_id
     *
     * @mbg.generated Fri Jun 25 12:16:42 CST 2021
     */
    public void setRoomId(String roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column play.room_name
     *
     * @return the value of play.room_name
     *
     * @mbg.generated Fri Jun 25 12:16:42 CST 2021
     */
    public String getRoomName() {
        return roomName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column play.room_name
     *
     * @param roomName the value for play.room_name
     *
     * @mbg.generated Fri Jun 25 12:16:42 CST 2021
     */
    public void setRoomName(String roomName) {
        this.roomName = roomName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column play.film_id
     *
     * @return the value of play.film_id
     *
     * @mbg.generated Fri Jun 25 12:16:42 CST 2021
     */
    public String getFilmId() {
        return filmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column play.film_id
     *
     * @param filmId the value for play.film_id
     *
     * @mbg.generated Fri Jun 25 12:16:42 CST 2021
     */
    public void setFilmId(String filmId) {
        this.filmId = filmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column play.film_name
     *
     * @return the value of play.film_name
     *
     * @mbg.generated Fri Jun 25 12:16:42 CST 2021
     */
    public String getFilmName() {
        return filmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column play.film_name
     *
     * @param filmName the value for play.film_name
     *
     * @mbg.generated Fri Jun 25 12:16:42 CST 2021
     */
    public void setFilmName(String filmName) {
        this.filmName = filmName;
    }
}