package com.duing.dao;

import com.duing.entity.Play;
import java.util.List;

public interface PlayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table play
     *
     * @mbg.generated Fri Jun 25 12:16:42 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table play
     *
     * @mbg.generated Fri Jun 25 12:16:42 CST 2021
     */
    int insert(Play record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table play
     *
     * @mbg.generated Fri Jun 25 12:16:42 CST 2021
     */
    Play selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table play
     *
     * @mbg.generated Fri Jun 25 12:16:42 CST 2021
     */
    List<Play> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table play
     *
     * @mbg.generated Fri Jun 25 12:16:42 CST 2021
     */
    int updateByPrimaryKey(Play record);

    List<Play> selectByFilmId(String filmId);

    Play selectByPlayId(String playId);
}